### ISSUE TITLE
Docker logs claim that eldorado.exe is not present

### ISSUE THREAD

**Issue by amrelk** [DomiStyle/docker-eldewrito#15]
I apologize if this is blatantly obvious and I am just making a stupid mistake, but I'm fairly sure that I'm not doing anything too dumb, so here is my issue: when I start the container with `docker-compose up -d`, the log files say that eldorado.exe could not be found. I'm guessing this is a configuration issue, but I don't really know.

My docker-compose.yml file (located at /home/dew/):
```yml
version: '2'
services:
  eldewrito:
    image: domistyle/eldewrito:0.6-test7
    restart: always
    ports:
      - 11774:11774/udp
      - 11775:11775/tcp
      - 11776:11776/tcp
      - 11777:11777/tcp
    volumes:
      - /home/dew/game:/game
      - /home/dew/config:/config
      - /home/dew/logs:/logs
    cap_add:
      - SYS_PTRACE
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - INSTANCE_ID=srv1
```

output of ls /home/dew/game (to show that eldorado.exe is really there):
```
ls /home/dew/game

binkw32.dll      custom_menu.exe     d3dcompiler_47.dll  eldorado.visualelementsmanifest.xml  libEGL.dll     maps        natives_blob.bin   tile-small.png      widevinecdmadapter.dll
chrome_elf.dll   custom_menu.log     dorito.log          icudtl.dat                           libGLESv2.dll  mods        snapshot_blob.bin  updater.exe
crashmodule.bin  d3dcompiler_43.dll  eldorado.exe        libcef.dll                           Logs           mtndew.dll  tile.png           updater.exe.config
```

Any ideas as to what I am doing wrong?
ps: this is on CentOS 7.
