### ISSUE TITLE
0009:warn:winsock:WS2_recv_base  -> ERROR 10035

### ISSUE THREAD

**Issue by Sphyrna-029** [DomiStyle/docker-eldewrito#20]
OS: Ubuntu 18.04.4 LTS
Docker: Docker version 19.03.6, build 369ce74a3c

Server shows up in browser but times out on connection. Enabled debug for wine and this error is flooding the logs.

```
0009:warn:winsock:WS2_recv_base  -> ERROR 10035
```

Server meta data is accessible at 11775, I can connect to all tcp ports with netcat except 11776 (suspecting this is where the issue is). Trying to run two servers in multi-instance mode but issue seems to persist even when running just one server. 

docker-compose.yml
```
eldewrito:
    image: domistyle/eldewrito
    restart: always
    ports:
      - 11774:11774/udp
      - 11775:11775/tcp
      - 11776:11776/tcp
      - 11777:11777/tcp
    volumes:
      - /home/eldewrito/game:/game
      - /home/eldewrito/config/srv1:/config
      - /home/eldewrito/logs/srv1:/logs
    cap_add:
      - SYS_PTRACE
    environment:
     #- RUN_AS_USER=1
     #- PUID=1000
     #- PGID=1000
      - WINE_DEBUG=1
      - SKIP_CHECKSUM_CHECK=1
      - INSTANCE_ID=srv1
```

Any help is appreciated.
